### ISSUE TITLE
Requires seperate .NET Runtime download

### ISSUE THREAD

**Issue by KosmosisDire** [flamewave000/ObsidianStartup#1]
When I try to run the program initially it throws an error that I must install the .NET runtime 6.0 to be able to use the program. I am not really sure if there is a way to get around this or if the runtime can be included with the program but it would make running the program initially quicker. Once it is installed though it works fine, so not a big deal overall. Thanks for creating this, it is very helpful :)

**Comment by flamewave000** [comment]
So I tried doing that, but it made the app over 150MiB in size, and I figure most people will have the .NET runtime already installed since its a fairly common dependency on Windows.

**Comment by OuOu2021** [comment]
.Net 6 is still not pre-installed in Windows 11(23H2). Is it possible to use .NET 4.8.1, which is built-in in Win10/11, to do the same thing?
